source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'iodine', '~> 0.7.37'
gem 'foreman', require: false

gem 'roda', '~> 3.25.0'

gem 'opal', github: 'janbiedermann/opal', branch: 'es6_modules_1_1'
gem 'opal-activesupport', '~> 0.3.3'
gem 'opal-webpack-loader', '>= 0.9.7'

gem 'isomorfeus-redux', '~> 4.0.16'
gem 'isomorfeus-react', path: '..'

group :test do
  gem 'rspec', '~> 3.8.0'
  gem 'isomorfeus-puppetmaster', '~> 0.3.0'
end
