source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'puma', '~> 5.3.1'
gem 'foreman', require: false

gem 'roda', '~> 3.44.0'

gem 'opal', github: 'janbiedermann/opal', branch: 'es6_modules_1_1'
gem 'opal-webpack-loader', '>= 0.11.0'

gem 'isomorfeus-redux', '~> 4.1.1'
gem 'isomorfeus-react', path: '..'

group :test do
  gem 'rspec', '~> 3.8.0'
  gem 'isomorfeus-puppetmaster', '~> 0.4.0'
end
