source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'iodine', '~> 0.7.38'
gem 'foreman', require: false

gem 'roda', '~> 3.29.0'

gem 'opal', github: 'janbiedermann/opal', branch: 'es6_modules_1_1'
gem 'opal-webpack-loader', '>= 0.9.10'

gem 'isomorfeus-redux', '~> 4.0.16'
gem 'isomorfeus-react', path: '..'

group :test do
  gem 'rspec', '~> 3.8.0'
  gem 'isomorfeus-puppetmaster', '~> 0.3.5'
end
