source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'iodine', '~> 0.7.57'

gem 'roda', '~> 3.79.0'

gem 'isomorfeus-react', path: '..'

group :test do
  gem 'rspec', '~> 3.13.0'
  gem 'isomorfeus-puppetmaster', '~> 0.9.3'
end
