source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'iodine', '~> 0.7.33'
gem 'foreman', require: false

gem 'roda', '~> 3.22.0'

gem 'opal', github: 'janbiedermann/opal', branch: 'es6_modules_1_1'
gem 'opal-webpack-loader', '>= 0.9.4'

gem 'isomorfeus-redux', '~> 4.0.14'
gem 'isomorfeus-react', path: '..'

group :development do
  gem 'auto_reloader'
end

group :test do
  gem 'rspec', '~> 3.8.0'
  gem 'isomorfeus-puppetmaster', '~> 0.2.9'
end
