source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'iodine', '~> 0.7.57'
gem 'foreman', require: false

gem 'roda', '~> 3.79.0'

gem 'opal'
gem 'isomorfeus-react', path: '..'

group :test do
  gem 'rspec', '~> 3.8.0'
  gem 'isomorfeus-puppetmaster', '~> 0.4.1'
end
