source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'puma'
gem 'roda', '~> 3.79.0'

gem 'opal', git: 'https://github.com/janbiedermann/opal.git', branch: 'rack'
# gem 'opal', path: '../../opal'
gem 'isomorfeus-react', path: '..'

group :test do
  gem 'rspec', '~> 3.8.0'
end
