name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 3.3
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.3.1
    - name: Build and test with Rake
      run: |
        gem install bundler
        rake
